### ISSUE TITLE
关于soutubot

### ISSUE THREAD

**Issue by ShellyMon** [luoxuebinfei/luo_bot#4]
![81b8e1f6b4e8171407d58230e6621e72](https://github.com/luoxuebinfei/luo_bot/assets/48594597/ee730774-8345-4bd0-8a0d-f480154ea48f)
soutubot的cf盾关了，想到前几天就有点难受了

**Comment by ShellyMon** [comment]
现在正常使用也使用不了了，唉~，联系不上作者

**Comment by luoxuebinfei** [comment]
sad😥，但应该不是我干的，我这才几个人用啊😭

**Comment by ShellyMon** [comment]
没有怪你的意思，这次cf盾撤销之后，确实卡了不少

**Comment by luoxuebinfei** [comment]
cf盾没了就被挤爆了，但我觉得再怎么使用爬虫搜图也不应该这样，我怀疑是被ddos了🤔

**Comment by ShellyMon** [comment]
可能是吧，实际上我觉得soutubot没有别的替代品啊

**Comment by ShellyMon** [comment]
我基本上一天调用个十次左右的接口

**Comment by luoxuebinfei** [comment]
tg群内部的使用好像已经恢复了

**Comment by ShellyMon** [comment]
那是什么，

**Comment by luoxuebinfei** [comment]
就是作者开发这网站前的一个搜图群组，现在好像是私密了进不去新人，这里面有群主的机器人可以使用Soutubot

**Comment by ShellyMon** [comment]
Soutubot机器人我加了，但是群组我没加

**Comment by ShellyMon** [comment]
怎么加群？

**Comment by luoxuebinfei** [comment]
私密了吧，看不到链接和邀请选项

**Comment by ShellyMon** [comment]
你会做推特的接口吗？我想获取推特上的图片

**Comment by luoxuebinfei** [comment]
获取推特图片？github上不是有很多这种项目吗？

**Comment by ShellyMon** [comment]
居然会这样，你推荐一个，我去抄

**Comment by luoxuebinfei** [comment]
https://github.com/KurtBestor/Hitomi-Downloader
https://github.com/mengzonefire/twitter-media-downloader
https://github.com/search?q=twitter%20download&type=repositories
——————————————————————
其实还有个问题是马一龙收购后限制了原本的api，不然可以直接使用api操作

**Comment by ShellyMon** [comment]
这两个我都看了一下，需要登陆推特获取cookie才能获取到资源，感觉还行，挺理想的，看看具体咋操作的

**Comment by ShellyMon** [comment]
但是我发现推特的图不清楚啊，可恶

**Comment by ShellyMon** [comment]
推特没有查看原图这种类似的操作么

**Comment by luoxuebinfei** [comment]
https://www.ganbey.com/download-twitter-images-3760

**Comment by ShellyMon** [comment]
好好好

**Comment by ShellyMon** [comment]
我现在也不想自己维护了，还是用你的吧233

**Comment by ShellyMon** [comment]
hello，作者，假设我安装了gocqhttp。那我还需要按照下面得指令进行安装吗
nb plugin install nonebot-plugin-apscheduler
nb plugin install nonebot-plugin-gocqhttp
nb plugin install nonebot-plugin-reboot

**Comment by ShellyMon** [comment]
可以不可以加个联系方式？

**Comment by luoxuebinfei** [comment]
> hello，作者，假设我安装了gocqhttp。那我还需要按照下面得指令进行安装吗 nb plugin install nonebot-plugin-apscheduler nb plugin install nonebot-plugin-gocqhttp nb plugin install nonebot-plugin-reboot

除了第一个其他都是可选的，已经装了gocqhttp就不用再用插件了，reboot插件只是用来在QQ发送机器人重启命令的，linux安装好像有问题。

**Comment by ShellyMon** [comment]
> > hello，作者，假设我安装了gocqhttp。那我还需要按照下面得指令进行安装吗 nb plugin install nonebot-plugin-apscheduler nb plugin install nonebot-plugin-gocqhttp nb plugin install nonebot-plugin-reboot
> 
> 除了第一个其他都是可选的，已经装了gocqhttp就不用再用插件了，reboot插件只是用来在QQ发送机器人重启命令的，linux安装好像有问题。

我把go-cqhttp的监听端口更换成了6700会报错，你这个连接方式是http还是ws？

**Comment by ShellyMon** [comment]
![image](https://github.com/luoxuebinfei/luo_bot/assets/48594597/94d88911-f9ff-4be1-8018-7541ae10891c)

**Comment by ShellyMon** [comment]
![image](https://github.com/luoxuebinfei/luo_bot/assets/48594597/3c34f24d-2144-43b1-bc97-23d980eb1ff6)
看起来是http，但是报404的错误

**Comment by ShellyMon** [comment]
![Uploading image.png…]()
go-cqhttp端的报错

**Comment by luoxuebinfei** [comment]
> > > hello，作者，假设我安装了gocqhttp。那我还需要按照下面得指令进行安装吗 nb plugin install nonebot-plugin-apscheduler nb plugin install nonebot-plugin-gocqhttp nb plugin install nonebot-plugin-reboot
> > 
> > 
> > 除了第一个其他都是可选的，已经装了gocqhttp就不用再用插件了，reboot插件只是用来在QQ发送机器人重启命令的，linux安装好像有问题。
> 
> 我把go-cqhttp的监听端口更换成了6700会报错，你这个连接方式是http还是ws？

`gocqhttp`的`config.yml`文件中的连接方式按照下面的格式改，端口修改为你要的端口
```
# 连接服务列表
servers:
  # 添加方式，同一连接方式可添加多个，具体配置说明请查看文档
  #- http: # http 通信
  #- ws:   # 正向 Websocket
  #- ws-reverse: # 反向 Websocket
  #- pprof: #性能分析服务器
  # 反向WS设置
  - ws-reverse:
      # 反向WS Universal 地址
      # 注意 设置了此项地址后下面两项将会被忽略
      universal: ws://127.0.0.1:8080/onebot/v11/ws
      # 反向WS API 地址
      api: ws://your_websocket_api.server
      # 反向WS Event 地址
      event: ws://your_websocket_event.server
      # 重连间隔 单位毫秒
      reconnect-interval: 3000
      middlewares:
        <<: *default # 引用默认中间件
```
机器人的`.env`配置中的`PORT=8080   # 监听端口`也要修改
